import {
  isDevelopmentIdentity,
  validateAdapterResponse,
  type AdapterCapabilities,
} from '@cashu-fault-lab/adapter-contract';
import { mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  scaffoldAdapterProject,
  supportedAdapterLanguages,
  type AdapterTemplateLanguage,
} from '../src/adapter-init.js';

const requiredRoutes = [
  '/v1/capabilities',
  '/v1/reset',
  '/v1/requests',
  '/v1/send',
  '/v1/deliveries/',
  '/v1/ledger',
  '/v1/proofs',
] as const;

async function filesUnder(root: string): Promise<string[]> {
  const entries: string[] = [];
  const walk = async (directory: string, prefix = '') => {
    for (const item of await readdir(directory, { withFileTypes: true })) {
      const relative = prefix.length === 0 ? item.name : `${prefix}/${item.name}`;
      const absolute = join(directory, item.name);
      if (item.isDirectory()) await walk(absolute, relative);
      else entries.push(relative);
    }
  };
  await walk(root);
  return entries.sort();
}

async function generatedText(root: string): Promise<string> {
  const files = await filesUnder(root);
  const chunks = await Promise.all(
    files
      .filter((file) => !file.endsWith('.lock'))
      .map(async (file) => await readFile(join(root, file), 'utf8')),
  );
  return chunks.join('\n');
}

async function generatedCapabilities(
  root: string,
  language: AdapterTemplateLanguage,
): Promise<AdapterCapabilities> {
  const relativePath =
    language === 'typescript'
      ? 'src/contract.ts'
      : language === 'rust'
        ? 'src/contract.rs'
        : 'src/my_wallet/contract.py';
  const source = await readFile(join(root, relativePath), 'utf8');
  const match =
    language === 'typescript'
      ? /export const contract = (\{.*\}) as const satisfies/u.exec(source)
      : language === 'rust'
        ? /CAPABILITIES: &str = r#"(\{.*\})"#;/u.exec(source)
        : /model_validate\(\n(\{[\s\S]*\})\n\)/u.exec(source);
  if (match?.[1] === undefined) {
    throw new Error(`Generated ${language} capabilities could not be extracted`);
  }
  return JSON.parse(match[1]) as AdapterCapabilities;
}

describe('adapter project scaffolding', () => {
  it.each(supportedAdapterLanguages)(
    'generates a standalone %s adapter project',
    async (language) => {
      const directory = await mkdtemp(join(tmpdir(), `cashu-${language}-adapter-`));
      const output = join(directory, 'my-wallet');

      try {
        const result = await scaffoldAdapterProject({
          language,
          name: 'my-wallet',
          role: 'both',
          output,
        });

        expect(result.output).toBe(output);
        const files = await filesUnder(output);
        expect(files).toEqual(
          expect.arrayContaining([
            '.dockerignore',
            '.env.example',
            '.github/workflows/ci.yml',
            'Dockerfile',
            'README.md',
            'adapter-manifest.json',
          ]),
        );
        const text = await generatedText(output);
        expect(text).not.toMatch(/@cashu-fault-lab|workspace:\*/u);
        expect(text).toContain('/healthz');
        expect(text).toContain('Bearer');
        expect(text).toContain('N/A');
        expect(text).toContain('501');
        expect(text).toContain('Generated by Cashu Fault Lab adapter init');
        expect(text).toContain('specDigest: sha256:');
        expect(text).toContain('Development identities are not release provenance.');
        for (const route of requiredRoutes) {
          expect(text).toContain(route);
        }
        const expectedModelFile =
          language === 'typescript'
            ? 'src/models.ts'
            : language === 'rust'
              ? 'src/models.rs'
              : 'src/my_wallet/models.py';
        expect(files).toContain(expectedModelFile);
        const model = await readFile(join(output, expectedModelFile), 'utf8');
        if (language === 'typescript') {
          expect(model).toContain("readonly status: 'processing' | 'settled' | 'rejected';");
          expect(model).toContain('readonly detail_code: string;');
          expect(await readFile(join(output, 'src/server.ts'), 'utf8')).toContain(
            "server.post('/v1/reset', async () => ({ ok: true }))",
          );
        } else if (language === 'rust') {
          expect(model).toContain('pub enum DeliveryReceiptStatus');
          expect(model).toContain('pub status: DeliveryReceiptStatus');
          expect(model).toContain('pub detail_code: String');
          expect(await readFile(join(output, 'src/main.rs'), 'utf8')).toContain(
            '.route("/v1/reset", post(reset))',
          );
        } else {
          expect(model).toContain('status: Literal["processing", "settled", "rejected"]');
          expect(model).toContain('detail_code: str');
          expect(await readFile(join(output, 'src/my_wallet/main.py'), 'utf8')).toContain(
            'def reset() -> dict[str, bool]:',
          );
        }

        const capabilities = await generatedCapabilities(output, language);
        expect(validateAdapterResponse('capabilities', capabilities)).toEqual({ ok: true });
        expect(isDevelopmentIdentity(capabilities.implementation)).toBe(true);

        const manifest = JSON.parse(
          await readFile(join(output, 'adapter-manifest.json'), 'utf8'),
        ) as {
          readonly schemaVersion: number;
          readonly adapters: readonly [{ readonly id: string; readonly tokenEnv: string }];
        };
        expect(manifest).toEqual({
          schemaVersion: 1,
          adapters: [
            {
              id: 'my-wallet',
              url: 'http://127.0.0.1:4100',
              tokenEnv: 'MY_WALLET_TOKEN',
            },
          ],
        });
      } finally {
        await rm(directory, { recursive: true, force: true });
      }
    },
  );

  it('writes role-specific default capabilities', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'cashu-rust-receiver-'));
    const output = join(directory, 'receive-only');

    try {
      await scaffoldAdapterProject({
        language: 'rust',
        name: 'receive-only',
        role: 'receiver',
        output,
      });

      const text = await generatedText(output);
      expect(text).toContain('receiver');
      expect(text).not.toContain('"sender"');
      expect(text).toContain('"tier":"T0"');
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });

  it('refuses invalid names and non-empty destinations without leaving a temp project', async () => {
    const directory = await mkdtemp(join(tmpdir(), 'cashu-invalid-adapter-'));
    const output = join(directory, 'occupied');
    await writeFile(output, 'not a directory');

    try {
      await expect(
        scaffoldAdapterProject({
          language: 'typescript',
          name: '../bad',
          role: 'both',
          output: join(directory, 'bad'),
        }),
      ).rejects.toThrow(/project name/i);
      await expect(
        scaffoldAdapterProject({
          language: 'typescript',
          name: 'occupied',
          role: 'both',
          output,
        }),
      ).rejects.toThrow(/non-empty|exists/i);

      expect((await readdir(directory)).filter((entry) => entry.includes('.tmp-'))).toEqual([]);
      await expect(stat(output)).resolves.toBeDefined();
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });
});
