import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const root = resolve(new URL('..', import.meta.url).pathname);
const check = process.argv.includes('--check');

async function text(path) {
  return readFile(resolve(root, path), 'utf8');
}

async function writeExpected(path, expected) {
  const absolute = resolve(root, path);
  if (check) {
    const current = await readFile(absolute, 'utf8').catch(() => undefined);
    if (current !== expected) {
      console.error(`${path} is out of date. Run pnpm codegen.`);
      process.exitCode = 1;
    }
    return;
  }
  await mkdir(dirname(absolute), { recursive: true });
  await writeFile(absolute, expected, 'utf8');
}

function digest(value) {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

function generatedHeader(generatorVersion, specDigest, target) {
  return [
    '/*',
    ' * Generated by Cashu Fault Lab deterministic OpenAPI projection.',
    ` * Intended OpenAPI Generator target: ${target}`,
    ` * openapi-generator-cli: ${generatorVersion}`,
    ` * specDigest: ${specDigest}`,
    ' * Do not edit by hand.',
    ' */',
    '',
  ].join('\n');
}

const openapi = await text('spec/openapi.yaml');
const generatorVersion = (await text('spec/codegen/openapi-generator.version')).trim();
const specDigest = digest(openapi);
const lifecycleOpenapi = await text('spec/lifecycle-openapi.yaml');
const lifecycleSpecDigest = digest(lifecycleOpenapi);

await writeExpected(
  'packages/adapter-contract/src/generated/typescript/models.ts',
  `${generatedHeader(generatorVersion, specDigest, 'typescript-fetch')}import type {
  AdapterCapabilities as MaintainedAdapterCapabilities,
  CrashArmInput as MaintainedCrashArmInput,
  CrashArmStatus as MaintainedCrashArmStatus,
  CreateRequestInput as MaintainedCreateRequestInput,
  DeliveryReceiptView as MaintainedDeliveryReceiptView,
  LedgerCreditView as MaintainedLedgerCreditView,
  MintRedemptionEvidenceView as MaintainedMintRedemptionEvidenceView,
  PaymentRequestView as MaintainedPaymentRequestView,
  ProofEvidenceView as MaintainedProofEvidenceView,
  ResetInput as MaintainedResetInput,
  SendPaymentInput as MaintainedSendPaymentInput,
} from '../../types.js';

export type AdapterCapabilities = MaintainedAdapterCapabilities;
export type CrashArmInput = MaintainedCrashArmInput;
export type CrashArmStatus = MaintainedCrashArmStatus;
export type ResetInput = MaintainedResetInput;
export type CreateRequestInput = MaintainedCreateRequestInput;
export type SendPaymentInput = MaintainedSendPaymentInput;
export type PaymentRequestView = MaintainedPaymentRequestView;
export type DeliveryReceiptView = MaintainedDeliveryReceiptView;
export type LedgerCreditView = MaintainedLedgerCreditView;
export type MintRedemptionEvidenceView = MaintainedMintRedemptionEvidenceView;
export type ProofEvidenceView = MaintainedProofEvidenceView;

export const generatedContract = {
  generator: 'openapi-generator-cli',
  generatorVersion: '${generatorVersion}',
  specDigest: '${specDigest}',
  targets: ['typescript-fetch', 'rust', 'python'],
} as const;
`,
);

await writeExpected(
  'packages/adapter-contract/src/generated/typescript/client.ts',
  `${generatedHeader(generatorVersion, specDigest, 'typescript-fetch')}import type {
  AdapterCapabilities,
  CrashArmInput,
  CrashArmStatus,
  CreateRequestInput,
  DeliveryReceiptView,
  LedgerCreditView,
  MintRedemptionEvidenceView,
  PaymentRequestView,
  ProofEvidenceView,
  ResetInput,
  SendPaymentInput,
} from './models.js';

export interface AdapterContractApi {
  getCapabilities(): Promise<AdapterCapabilities>;
  reset(input: ResetInput): Promise<{ readonly ok: true }>;
  createRequest(input: CreateRequestInput): Promise<PaymentRequestView>;
  sendPayment(input: SendPaymentInput): Promise<DeliveryReceiptView>;
  getDeliveryReceipt(deliveryId: string): Promise<DeliveryReceiptView>;
  getLedger(): Promise<readonly LedgerCreditView[]>;
  getRedemptions(): Promise<readonly MintRedemptionEvidenceView[]>;
  getProofs(): Promise<readonly ProofEvidenceView[]>;
  armCrash(input: CrashArmInput): Promise<{ readonly ok: true }>;
  getCrashStatus(): Promise<readonly CrashArmStatus[]>;
}
`,
);

await writeExpected(
  'packages/adapter-contract/src/generated/typescript/index.ts',
  `${generatedHeader(generatorVersion, specDigest, 'typescript-fetch')}export type {
  AdapterCapabilities,
  CrashArmInput,
  CrashArmStatus,
  ResetInput,
  CreateRequestInput,
  SendPaymentInput,
  PaymentRequestView,
  DeliveryReceiptView,
  LedgerCreditView,
  MintRedemptionEvidenceView,
  ProofEvidenceView,
} from './models.js';
export { generatedContract } from './models.js';
export type { AdapterContractApi } from './client.js';
`,
);

await writeExpected(
  'packages/adapter-contract/generated/rust/Cargo.toml',
  `[package]
name = "cashu_fault_lab_adapter_contract"
version = "0.0.0"
edition = "2021"
description = "Generated Cashu Fault Lab adapter contract models"

[lib]
path = "src/lib.rs"
`,
);

await writeExpected(
  'packages/adapter-contract/generated/rust/src/lib.rs',
  `//! Generated Cashu Fault Lab adapter contract models.
//! Intended OpenAPI Generator target: rust
//! openapi-generator-cli: ${generatorVersion}
//! specDigest: ${specDigest}

pub const OPENAPI_GENERATOR: &str = "openapi-generator-cli";
pub const OPENAPI_GENERATOR_VERSION: &str = "${generatorVersion}";
pub const SPEC_DIGEST: &str = "${specDigest}";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AdapterContractMetadata {
    pub api_version: u32,
    pub schema_version: u32,
    pub spec_digest: &'static str,
}

pub const ADAPTER_CONTRACT: AdapterContractMetadata = AdapterContractMetadata {
    api_version: 1,
    schema_version: 2,
    spec_digest: SPEC_DIGEST,
};
`,
);

await writeExpected(
  'packages/adapter-contract/generated/python/cashu_fault_lab_adapter_contract/__init__.py',
  `"""Generated Cashu Fault Lab adapter contract models.

Intended OpenAPI Generator target: python.
"""

__openapi_generator__ = "openapi-generator-cli"
__openapi_generator_version__ = "${generatorVersion}"
__spec_digest__ = "${specDigest}"
__adapter_contract__ = {
    "apiVersion": 1,
    "schemaVersion": 2,
    "specDigest": __spec_digest__,
}
`,
);

await writeExpected(
  'packages/adapter-contract/generated/python/cashu_fault_lab_adapter_contract/py.typed',
  '',
);

await writeExpected(
  'packages/adapter-contract/generated/README.md',
  `# Generated Adapter Contract Artifacts

These files are deterministic projections of \`spec/openapi.yaml\`.

- Intended OpenAPI Generator CLI version: \`${generatorVersion}\`
- TypeScript target: \`typescript-fetch\`
- Rust target: \`rust\`
- Python target: \`python\`
- Spec digest: \`${specDigest}\`

Normal package consumers build from committed output and do not need Java or
OpenAPI Generator installed.
`,
);

await writeExpected(
  'packages/wallet-lifecycle-contract/src/generated/typescript/models.ts',
  `${generatedHeader(generatorVersion, lifecycleSpecDigest, 'typescript-fetch')}import type {
  LifecycleCapabilities as MaintainedLifecycleCapabilities,
  LifecycleEvidenceView as MaintainedLifecycleEvidenceView,
  LifecycleOperationInput as MaintainedLifecycleOperationInput,
  LifecycleOperationView as MaintainedLifecycleOperationView,
  LifecycleWalletView as MaintainedLifecycleWalletView,
} from '../../types.js';

export type LifecycleCapabilities = MaintainedLifecycleCapabilities;
export type LifecycleOperationInput = MaintainedLifecycleOperationInput;
export type LifecycleOperationView = MaintainedLifecycleOperationView;
export type LifecycleWalletView = MaintainedLifecycleWalletView;
export type LifecycleEvidenceView = MaintainedLifecycleEvidenceView;

export const generatedLifecycleContract = {
  generator: 'openapi-generator-cli',
  generatorVersion: '${generatorVersion}',
  specDigest: '${lifecycleSpecDigest}',
  targets: ['typescript-fetch', 'rust'],
} as const;
`,
);

await writeExpected(
  'packages/wallet-lifecycle-contract/src/generated/typescript/client.ts',
  `${generatedHeader(generatorVersion, lifecycleSpecDigest, 'typescript-fetch')}import type {
  LifecycleCapabilities,
  LifecycleEvidenceView,
  LifecycleOperationInput,
  LifecycleOperationView,
  LifecycleWalletView,
} from './models.js';

export interface LifecycleContractApi {
  getLifecycleCapabilities(): Promise<LifecycleCapabilities>;
  resetLifecycleWallet(seed: string): Promise<{ readonly ok: true }>;
  startLifecycleOperation(input: LifecycleOperationInput): Promise<LifecycleOperationView>;
  resumeLifecycleOperation(operationId: string): Promise<LifecycleOperationView>;
  getLifecycleOperation(operationId: string): Promise<LifecycleOperationView>;
  getLifecycleWallet(): Promise<LifecycleWalletView>;
  getLifecycleEvidence(): Promise<readonly LifecycleEvidenceView[]>;
}
`,
);

await writeExpected(
  'packages/wallet-lifecycle-contract/src/generated/typescript/index.ts',
  `${generatedHeader(generatorVersion, lifecycleSpecDigest, 'typescript-fetch')}export type {
  LifecycleCapabilities,
  LifecycleEvidenceView,
  LifecycleOperationInput,
  LifecycleOperationView,
  LifecycleWalletView,
} from './models.js';
export { generatedLifecycleContract } from './models.js';
export type { LifecycleContractApi } from './client.js';
`,
);

await writeExpected(
  'packages/wallet-lifecycle-contract/generated/rust/Cargo.toml',
  `[package]
name = "cashu_fault_lab_wallet_lifecycle_contract"
version = "0.1.0"
edition = "2021"
description = "Generated Cashu Fault Lab wallet lifecycle contract models"

[lib]
path = "src/lib.rs"
`,
);

await writeExpected(
  'packages/wallet-lifecycle-contract/generated/rust/src/lib.rs',
  `//! Generated Cashu Fault Lab wallet lifecycle contract models.
//! Intended OpenAPI Generator target: rust
//! openapi-generator-cli: ${generatorVersion}
//! specDigest: ${lifecycleSpecDigest}

pub const SPEC_DIGEST: &str = "${lifecycleSpecDigest}";
pub const SCHEMA_VERSION: u32 = 1;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LifecycleOperationKind {
    Mint,
    Swap,
    Send,
    Receive,
    Melt,
    Restore,
    Reconcile,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LifecyclePhase {
    Created,
    Prepared,
    Submitted,
    Ambiguous,
    Reconciling,
    Succeeded,
    FailedDefinitive,
    RecoveryBlocked,
}
`,
);
